
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emmanuel Ajayi
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
      */
    public Administrator() {
        initComponents();
        showTable();
        officeHours();
        jButton5.setEnabled(false);
        jButton4.setEnabled(true);
        
    }
    private  void    showTable(){  
            try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String sql = "Select * from login_statistics"  ;
            Statement st = con.prepareStatement(sql); 
            ResultSet rs = st.executeQuery(sql);
            Table_display.setModel(DbUtils.resultSetToTableModel(rs));
            String sq = "Select * from logout_statistics"  ;
            Statement stm = con.prepareStatement(sq); 
            ResultSet rst = st.executeQuery(sq);
            Table2.setModel(DbUtils.resultSetToTableModel(rst));
            

            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
           
    }
    private void officeHours(){
     try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String sql = "Select *  from time_worked"  ;
            Statement st = con.prepareStatement(sql); 
            ResultSet rs = st.executeQuery(sql);
            ofh.setModel(DbUtils.resultSetToTableModel(rs));
            
            

            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
    }
    private void showMessage(){
         try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String sql = "Select message  from messages"  ;
            Statement st = con.prepareStatement(sql); 
            ResultSet rs = st.executeQuery(sql);
            messageTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            

            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
    
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_display = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ofh = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mess = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATR BG.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 165, 32));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 165, 32));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGOUT1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 340, 70, 20);

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(590, 320, 50, 20);

        jButton4.setBackground(new java.awt.Color(0, 153, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DELETE ACCOUNT.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(150, 320, 130, 20);

        jButton5.setBackground(new java.awt.Color(0, 153, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEW ACCOUNT.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 320, 120, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATR BG.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 380);

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jPanel3.setLayout(null);

        Table_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "S/n", "Username", "Sign in"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table_display);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 40, 320, 90);

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sn", "Username", "Sign out"
            }
        ));
        jScrollPane1.setViewportView(Table2);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(320, 40, 330, 90);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 11, 370, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign out ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(320, 10, 100, 30);

        ofh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username ", "Time"
            }
        ));
        jScrollPane4.setViewportView(ofh);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(0, 220, 650, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Hours");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(74, 180, 240, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATR BG.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 660, 380);

        jTabbedPane1.addTab("Attendance Register", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        mess.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        mess.setForeground(new java.awt.Color(255, 165, 32));
        mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messActionPerformed(evt);
            }
        });
        jPanel2.add(mess);
        mess.setBounds(120, 230, 390, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEND.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(550, 230, 80, 30);

        user.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 165, 32));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N
        jPanel2.add(user);
        user.setBounds(10, 230, 90, 30);

        messageTable.setAutoCreateRowSorter(true);
        messageTable.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        messageTable.setForeground(new java.awt.Color(255, 165, 32));
        messageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(messageTable);
        if (messageTable.getColumnModel().getColumnCount() > 0) {
            messageTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 640, 132);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATR BG.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 660, 370);

        jTabbedPane1.addTab("Messages", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        showTable();
        officeHours();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void messActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFrame frame = new JFrame();
        
        if (JOptionPane.showConfirmDialog( frame, "Are you sure you want to  Sign out","Log out", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        
        {
        admin_log second = new admin_log ();
            second.setVisible(true);
            setVisible(false);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String query = "insert into messages(Username,message ) values(?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, user.getText() );
            ps.setString(2, mess.getText() );
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Message sent successfully !");
            mess.setText(" ");
            showMessage();
           
            
            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
        
                                 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        showMessage();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setEnabled(false);
        jButton4.setEnabled(true);
        register regist = new register();
        regist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         
         JFrame frame = new JFrame();
        
        if (JOptionPane.showConfirmDialog( frame, "Are you sure you want to  Delete the account","Delete account", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        
        {
         try {
            jButton5.setEnabled(true);
            jButton4.setEnabled(false);
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String sql = "Truncate employee";
            PreparedStatement pst = con.prepareStatement(sql);
           
          
            pst.executeQuery();
            

            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pass_reset rst = new pass_reset();
        rst.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table_display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mess;
    private javax.swing.JTable messageTable;
    private javax.swing.JTable ofh;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
