
import java.awt.Component;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emmanuel Ajayi
 */
public class Employee_p extends javax.swing.JFrame {
   private int millisec = 0;
   private  int sec = 0;
   private int min= 0;
   private int hr = 0;
   private boolean state = true;
   private int imagecount;
   private String Inum2,Inum, Inum3;
   private final String srn = "30";

    /**
     * Creates new form Employee_p
     */
    public Employee_p() {
        initComponents();
        
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
       time.setVisible(false);
       time1.setVisible(false);
       time2.setVisible(false);
       time3.setVisible(false);
       jLabel3.setVisible(false);
       user.setVisible(false);
      
        

    }
     private void showMessage(){
         try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String sql = "Select message from messages"  ;
            Statement st = con.prepareStatement(sql); 
            ResultSet rs = st.executeQuery(sql);
            messageTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            

            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
    
    
    }
     private void capture_screen(){
    try {
        Rectangle screenrect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
        BufferedImage capture = new Robot().createScreenCapture(screenrect);
        ImageIcon icon = new ImageIcon(capture);
        String filename = String.format("Screenshot-%d.png", this.imagecount);
        String directory = "C:\\Users\\Emmanuel Ajayi\\Pictures\\WFHP\\";
        ImageIO.write(capture,"png", new File(directory,filename)  );
        
        
        imagecount++;
        
        
        
    
    }
    catch(Exception e ){
    JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        record = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        check = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mess = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        user1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 165, 32));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 165, 32));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGOUT.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 230, 130, 40);

        jButton6.setBackground(new java.awt.Color(0, 153, 51));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BREAK.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(170, 190, 90, 30);

        user.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Employee");
        jPanel1.add(user);
        user.setBounds(0, 0, 190, 50);

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STart.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 190, 90, 30);

        jButton4.setText("Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(469, 250, 90, 30);

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(210, 270, 80, 40);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TIME SPENT.png"))); // NOI18N
        jLabel1.setText("Time spent");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 90, 180, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATUS.png"))); // NOI18N
        jLabel2.setText("Status");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 140, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel3.setText("Timer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 270, 103, 41);

        record.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        record.setForeground(new java.awt.Color(255, 255, 255));
        record.setText("0 mins");
        jPanel1.add(record);
        record.setBounds(240, 90, 230, 40);

        time.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        time.setText("00:");
        jPanel1.add(time);
        time.setBounds(290, 270, 51, 51);

        check.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("Off");
        jPanel1.add(check);
        check.setBounds(180, 140, 170, 30);

        time1.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        time1.setText("00:");
        jPanel1.add(time1);
        time1.setBounds(250, 270, 56, 51);

        time2.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        time2.setText("00:");
        jPanel1.add(time2);
        time2.setBounds(330, 270, 59, 51);

        time3.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        time3.setText("0000");
        jPanel1.add(time3);
        time3.setBounds(370, 270, 59, 51);
        jPanel1.add(show);
        show.setBounds(0, 340, 146, 83);

        jButton7.setBackground(new java.awt.Color(0, 153, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(210, 240, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STATR BG.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 640, 350);

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEND.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        user1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        user1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HI.png"))); // NOI18N
        user1.setText("Employee");

        messageTable.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        messageTable.setForeground(new java.awt.Color(255, 165, 32));
        messageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(messageTable);
        if (messageTable.getColumnModel().getColumnCount() > 0) {
            messageTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            messageTable.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mess, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Messages", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFrame frame = new JFrame();
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog( frame, "Are you sure you want to  Sign out","Log out", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        
        {
         state = false;
    
         try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String query = "insert into logout_statistics(Username ) values(?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, user.getText() );
            ps.executeUpdate();
            String  qry = "insert into time_worked(Username, Time ) values(?,?)";
            PreparedStatement pst = con.prepareStatement(qry);
            pst.setString(1, user.getText() );
            pst.setString(2, record.getText());
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null, "log out successfull !");
            Login second = new Login ();
            second.setVisible(true);
            setVisible(false);
            
            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void messActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           try {
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wfh", "root","yincuzi" );
            String query = "insert into messages(Username,message ) values(?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, user.getText() );
            ps.setString(2, mess.getText() );
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Message sent successfully !");
            mess.setText(" ");
            showMessage();
           
            
            con.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        showMessage();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        state =true;
        jButton3.setEnabled(false);
        Thread t = new Thread(){
            public void run(){
                for (;;)   {
                    if (state == true ){
                        try{
                            sleep(1);
                            if (millisec>1000){
                                millisec =0;
                                sec++;
                            }
                            if (sec>60){
                                millisec =0;
                                sec = 0;
                                min++;
                            }
                            if (min>60){
                                millisec =0;
                                sec = 0;
                                min =0;
                                hr++;
                            }
                            time3.setText(":" + millisec) ;
                            millisec++;
                          
                            time.setText("" + hr +":");
                            time1.setText( " " + min);
                            time2.setText("" + sec);
                            Inum = time1.getText();
                            Inum2 = time2.getText();
                            Inum3 = time.getText();
                            record.setText(Inum3+Inum + ":"+Inum2+  " Hours");
                            a:if( Inum2.equals(srn)){
                                capture_screen();
                                sec++;

                            }

                        }
                        catch(Exception e){}

                    }
                    else {
                        break;
                    }
                }}
            };
            t.start();
            check.setText("Working ");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        state =false;
        String Inum = time1.getText();
        String Inum2 = time2.getText();
        record.setText(Inum + Inum2+  " mins");
        check.setText("Off");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        millisec = 0;
        sec = 0;
        min= 0;
        hr = 0;
        time.setText("00:" );
        time1.setText("00:" );
        time2.setText("00:" );
        time3.setText("0000" ) ;
        record.setText("0 mins");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
       
       

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        state = false;
         jButton6.setEnabled(state);
         jButton3.setEnabled(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        emp_res ep = new emp_res();
        ep.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_p().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel check;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mess;
    private javax.swing.JTable messageTable;
    private javax.swing.JLabel record;
    private javax.swing.JLabel show;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    // End of variables declaration//GEN-END:variables
}
